apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example
  annotations:
    # don't redirect HTTP to HTTPS
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: <FQDN>
    http:
      paths:
      - backend:
          service:
            name: knote
            port:
              number: 80
        path: /
        pathType: Prefix
      - backend:
          service:
            name: app-java
            port:
              number: 80
        path: /app-java-0.0.1-SNAPSHOT/
        pathType: Prefix
