apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    clusterName: operator-cluster
    credentials:
      apiSecret:
        secretName: datadog-agent
        keyName: api-key
      appSecret:
        secretName: datadog-agent
        keyName: app-key
    kubelet:
      tlsVerify: false
  features:
    logCollection:
      enabled: true
    liveProcessCollection:
      enabled: true
    liveContainerCollection:
      enabled: true
    processDiscovery:
      enabled: true
    oomKill:
      enabled: true
    tcpQueueLength:
      enabled: true
    ebpfCheck:
      enabled: false
    apm:
      enabled: true
    cspm:
      enabled: false
    cws:
      enabled: false
    npm:
      enabled: false
    usm:
      enabled: false
    dogstatsd:
      unixDomainSocketConfig:
        enabled: false
    otlp:
      receiver:
        protocols:
          grpc:
            enabled: false
    remoteConfiguration:
      enabled: true
    sbom:
      enabled: true
    eventCollection:
      collectKubernetesEvents: true
    orchestratorExplorer:
      enabled: true
    kubeStateMetricsCore:
      enabled: true
    admissionController:
      enabled: true
    externalMetricsServer:
      enabled: true
    clusterChecks:
      enabled: true
    prometheusScrape:
      enabled: true
