apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: py-test-tracer
    tags.datadoghq.com/env: "dev"
    tags.datadoghq.com/service: "pyflask_hello_world"
    tags.datadoghq.com/version: "1"
  name: py-test-tracer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-test-tracer
  template:
    metadata:
      labels:
        app: py-test-tracer
        tags.datadoghq.com/env: "dev"
        tags.datadoghq.com/service: "pyflask_hello_world"
        tags.datadoghq.com/version: "1"
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/python-lib.version: "v2.5.5"
    spec:
      containers:
      - image: jenksgibbons/pyflask_hello_world:tracer_txt
        name: pyflask-hello-world
