apiVersion: v1
kind: Service
metadata:
  labels:
    run: aspnc
  name: aspnc
  namespace: default
spec:
  ports:
  - nodePort: 30649
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: aspnc
  type: NodePort
