apiVersion: v1
kind: Pod
metadata:
  labels:
    run: aspnc
  name: aspnc
  namespace: default
spec:
  containers:
  - env:
    - name: CORECLR_ENABLE_PROFILING
      value: "1"
    - name: CORECLR_PROFILER_PATH_64
      value: "<FILL_IN>"
    - name: CORECLR_PROFILER
      value: "<INSERT_VALUE_HERE>"
    - name: LD_LIBRARY_PATH
      value: "<FILL_IN>"
    - name: LD_PRELOAD
      value: "<FILL_IN"
    - name: DD_ENV
      value: "<FILL_IN>"
    - name: DD_SERVICE
      value: "<FILL_IN>"
    - name: DD_VERSION
      value: "<FILL_IN"
    - name: DD_AGENT_HOST
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    image: jenksgibbons/aspnc
    imagePullPolicy: IfNotPresent
    name: aspnc
