# relative to dev directory so default should be fine  
kind:
  repo_path: "kubernetes/kind"
  cluster_kubeconfig: "./config"

# this is used for app-java RUM to set values for the Datadog tokens  
secret:
  - generic:
      name: dd-rum-tokens
      secret_key_0: "APPLICATION_ID"
      value_0: <APPLICATION_ID>
      secret_key_1: "CLIENT_TOKEN"
      value_1: <CLIENT_TOKEN>

# all manifests in deployment - three here as app-java has three  
application:
  - object:
      manifest: <MANIFEST_1>
      namespace: <NAMESPACE>
      label_selector: <LABEL_SELECTOR_1>
  - object:
      manifest: <MANIFEST_2>
      namespace: <NAMESPACE>
      label_selector: <LABEL_SELECTOR_2>
  - object:
      manifest: <MANIFEST_3>
      namespace: ""
      label_selector: ""

# Datadog [CI configuration](https://docs.datadoghq.com/continuous_testing/cicd_integrations/configuration/?tab=npm)
browser_test:
  skip: False
  # test to run
  id_config: "cicd.synthetics.json"
  # start url and tunnel option
  tunnel_config: "datadog-ci.json"
  # public id of test from browser test UI in Datadog
  public_id: <BROWSER_TEST_PUBLIC_ID>
  # tunnel port
  tunnel_port: <BROWSER_TEST_TUNNEL_PORT>
  # app port
  app_port: <BROWSER_TEST_APP_PORT>

# port forward type and name (e.g. deploy/app-java)
port_forward:
  type_name: <PORT_FORWARD_TYPE_NAME>

# local functions
modules:
  cicd: "./local_cicd_functions.py"
  module_relative_path: "../cicd_functions.py"

# service name (e.g. app-java, petclinic)
service:
  name: <SERVICE_NAME>