name: Java CI

on: [push]

jobs:
  vulnerability_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Compute dependency graph
        run: docker run -e "SNYK_TOKEN=$SNYK_TOKEN" -v "$PWD:/project" snyk/snyk-cli:maven-3.6.3_java11 test --print-deps --json --file=app/pom.xml > deps.json
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload dependency graph to Datadog
        uses: datadog/github-action-vulnerability-analysis@v0.3
        with:
          service: 'java-app'
          version: 'v.01'
          site: 'datadoghq.com'
        env:
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          DATADOG_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}
