on: [push]

name: Datadog Software Composition Analysis

jobs:
  software-composition-analysis:
    runs-on: ubuntu-latest
    name: Datadog SBOM Generation and Upload
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Check imported libraries are secure and compliant
      id: datadog-software-composition-analysis
      uses: DataDog/datadog-sca-github-action@main
      with:
        dd_api_key: ${{ secrets.DATADOG_API_KEY }}
        dd_app_key: ${{ secrets.DATADOG_APP_KEY }}
        dd_app_key: ${{ secrets.DD_APP_KEY }}
        dd_service: app-java
        dd_env: ci
        dd_site: datadoghq.com
