name: docker_build
on: [push]
jobs:
  build:
    environment: datadog
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: install libraries
        env:
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
        run: |
          pushd kubernetes/nodejs_tracing/dockerfile_configuration/
          docker build -t jenksgibbons/knote .
        shell: bash
