name: docker_build
on: 
  push:
    branches:    
      - no_dot_net_tracer
jobs:
  build:
    environment: datadog
    runs-on: windows-2019 #windows-latest #windows-2019
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: build and push image
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          pushd docker/aspnet48_mvc_app/aspnet48_mvc_win_server_core_ltsc_2019_app/
          echo $DOCKER_PASSWORD > docker.txt
          cat docker.txt | docker login --username jenksgibbons --password-stdin
          docker build -t jenksgibbons/win_dotnetcore:win_2019_no_tracer -f Dockerfile.ecs.no_tracer .;docker push jenksgibbons/win_dotnetcore:win_2019_no_tracer
        shell: bash
