name: docker_build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: build and push image
        run: |
          cat <<EOT >> dockerfile
          FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
          WORKDIR /app
          EXPOSE 80
          EXPOSE 443

          FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
          FROM base AS final

          ARG DD_TRACER_VERSION=2.29.0
          ENV DD_TRACER_VERSION=$DD_TRACER_VERSION
          
          ENV CORECLR_ENABLE_PROFILING=1
          ENV CORECLR_PROFILER={846F5F1C-F9AE-4B07-969E-05C26BC060D8}
          ENV CORECLR_PROFILER_PATH=/datadog/Datadog.Trace.ClrProfiler.Native.dll
          ENV DD_DOTNET_TRACER_HOME=/datadog
          ENV DD_INTEGRATIONS=/datadog/integrations.json

          ENTRYPOINT ["dotnet", "DatadogContainerExample.dll"]
          EOT
          docker build -t jenksgibbons/win_test .
          docker ps
        shell: bash
